
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: back-end-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: back
  template:
    metadata:
      labels:
        component: back
    spec:
      containers:
        - name: flask-back-end
          image: shajalahamedcse/react-backend:0.0.1
          ports:
            - containerPort: 5000
        